# Generated by Django 5.0.7 on 2025-10-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_app', '0003_cpp_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Java_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=1255)),
                ('option1', models.CharField(max_length=1000)),
                ('option2', models.CharField(max_length=1000)),
                ('option3', models.CharField(max_length=1000)),
                ('option4', models.CharField(max_length=1000)),
                ('correct_answer', models.CharField(max_length=1000)),
            ],
        ),
    ]
